services:
  postgres:
    env_file:
      - .env
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
